language: generic

sudo: required

services:
        - docker

before_install:
        - docker build -t lexsteens/docker-react -f Dockerfile.dev .


script:
        - docker run -e CI=true lexsteens/docker-react npm run test
