language: generic

sudo: required

services:
        - docker

before_install:
        - docker build -t lexsteens/docker-react -f Dockerfile.dev .


script:
        - docker run -e CI=true lexsteens/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "eu-west-1"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-eu-west-1-048628274615"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: "$access_key_id"
        secret_access_key: "$secret_access_key"
